# https://cloud.google.com/appengine/docs/standard/ruby/config/appref
runtime: ruby26
service: default
entrypoint: bundle exec rails server
env_variables:
  RAILS_ENV: development
  NODE_ENV: development

# Performance Options
instance_class: "F2"  # https://cloud.google.com/appengine/docs/standard#instance_classes
